name: "Build Page"
permissions:
  contents: read
  pages: write
  id-token: write
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix build
    - name: Upload a Build Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: "./result/book"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v2
